default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")

    increment_build_number(
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "App/VerseSnap.xcodeproj"
    )

    build_app(scheme: "App-prod")
    upload_to_testflight
  end
end
